Add the encryptedfile to eventcontent
quotient-im/libQuotient pull request #505
Opened 2021-09-10 15:34 UTC by TobiasFella

2021-09-13 17:15 UTC, TobiasFella commented
Changed to be against the master branch instead. There really isn't anything in here that required the other parts of the E2EE work to compile (of course you're never going to see an encryptedfile in unencrypted events)

2021-09-18 12:47 UTC, KitsuneRal requested changes
LGTM, just a couple of nitpicks.

2021-09-18 12:47 UTC, KitsuneRal commented on lib/events/encryptedfile.h
> +#include <QObject>
```suggestion
```
If it's for `Q_GADGET`, `quotient_common.h` (included via `converters.h`) already includes a necessary Qt header.

2021-09-18 14:20 UTC, KitsuneRal approved these changes

2021-09-18 14:20 UTC, merged