Add convenience function for activating encryption
quotient-im/libQuotient pull request #506
Opened 2021-09-11 14:20 UTC by TobiasFella

...and fix EncryptionEvent constructor

2021-09-11 18:39 UTC, KitsuneRal requested changes

2021-09-11 18:39 UTC, KitsuneRal commented on lib/room.cpp
> +        qCWarning(E2EE) << "This room is already encrypted";
```suggestion
        qCWarning(E2EE) << "Room" << objectName() << "is already encrypted";
```
It's not always easy to discern to which room the log line pertains; better to identify it right in the log line.

2021-09-11 18:39 UTC, KitsuneRal commented on lib/room.cpp
> +    qWarning() << evt
?

2021-09-11 19:01 UTC, TobiasFella commented on lib/room.cpp
> +    qWarning() << evt
no idea what happened there...

2021-09-12 08:04 UTC, KitsuneRal approved these changes

2021-09-12 08:04 UTC, merged