Add method to get all state events in a room
quotient-im/libQuotient pull request #518
Opened 2021-11-07 14:46 UTC by Smittyvb

It is useful to be able to get all of the state events that have occurred in a room, instead of needing to use `Room::getCurrentState`, which filters based on the event type and state key.

This is useful for implementing Spaces support, where all events of type `m.space.child` are needed, and we don't know their state keys in advance.

2021-11-07 16:39 UTC, KitsuneRal requested changes
Thanks for the contribution, but there's one shortcoming with it: if a room has 10k members, or another kind of heavy state, every `stateEvents()` invitation will lead to copying all of that state into the returned list (fortunately only pointers will be copied but that can be still a lot). If you really want, for whatever reason, to obtain the whole current state, you might better just return a const reference to the internal `currentState` container, in the same way `messageEvents()` returns a const reference to the timeline. On the other hand, if you need all events of a particular type such as `m.space.child` filtering on the original container is more efficient - basically, you could pass the event type parameter to the function so that it could collect all such events for you. I'm fine if you implement either option; but ideally it'd be great to have both.

2021-11-07 23:12 UTC, Smittyvb commented
@KitsuneRal I've updated the PR to make `stateEvents` return the inner `QHash`, and `stateEventsOfType` return a list of the state events of a type.

2021-11-21 15:44 UTC, KitsuneRal requested changes
Thanks! I have quite a few technical comments to the code but the overall direction is right. Sorry if I missed something - didn't try to compile all the suggestions.

2021-11-21 15:44 UTC, KitsuneRal commented on lib/room.cpp
> +const QList<const StateEventBase*>*
That's not quite what I was looking for: returning a dynamically allocated `QList` will surely lead to people forgetting to `delete` it afterwards, let alone being inefficient since `QList` is [implicitly-shared](https://doc.qt.io/qt-5/implicit-sharing.html) anyway. Also - `QVector` is equally or more efficient compared to `QList` and [should be used by default](https://doc.qt.io/qt-5/qlist.html#details) (in fact, Qt 6 has `QVector` and `QList` referring to the same class, and it's basically Qt 5's `QVector`).
```suggestion
QVector<const StateEventBase*>
```

2021-11-21 15:44 UTC, KitsuneRal commented on lib/room.cpp
> +const QHash<StateEventKey, const StateEventBase*> Room::stateEvents() const
`QHash` is implicily-shared so copying it is cheap - but it could just be a reference, couldn't it? (Assuming that `Q_INVOKABLE` doesn't work, see the next comment.)
Also: `stateEvents()` is not specific enough, since `Room` actually maintains several (two, as of now) sets of state events. The base state is not exposed in the API as yet but it might be in the future - e.g. as a part of the protected API.
```suggestion
const QHash<StateEventKey, const StateEventBase*>& Room::currentState() const
```

2021-11-21 15:44 UTC, KitsuneRal commented on lib/room.h
> +    Q_INVOKABLE const QHash<StateEventKey, const StateEventBase*> stateEvents() const;
As much as I'd like it to work, I don't think `Q_INVOKABLE` is very useful here: AFAIK `QHash` is not converted to anything on QML/JavaScript side, you'd have to use `QVariantMap` instead. As conversion to `QVariantMap` is quite straightforward I'd prefer to leave that to clients and just give access to the original hash-map.
```suggestion
    const QHash<StateEventKey, const StateEventBase*>& currentState() const;
```

2021-11-21 15:44 UTC, KitsuneRal commented on lib/room.h
> +    Q_INVOKABLE const QList<const StateEventBase*>*
Unlike the above, `Q_INVOKABLE` is fine here, with `QVector` being converted to a JavaScript array on the QML side (see https://doc.qt.io/qt-5/qtqml-cppintegration-data.html#sequence-type-to-javascript-array) thanks to `const StateEventBase*` being marked with `Q_DECLARE_METATYPE`.
```suggestion
    Q_INVOKABLE QVector<const StateEventBase*>
```

2021-11-21 15:44 UTC, KitsuneRal commented on lib/room.cpp
> +
This is unneeded as we're already in the internal implementation domain.
```suggestion
```

2021-11-21 15:44 UTC, KitsuneRal commented on lib/room.cpp
> +    return d->stateEvents();
```suggestion
    return d->currentState;
```

2021-11-21 15:44 UTC, KitsuneRal commented on lib/room.cpp
> +    stateEventsOfType(const QString& evtType) const
```suggestion
    QVector<const StateEventBase*> stateEventsOfType(const QString& evtType) const
```

2021-11-21 15:44 UTC, KitsuneRal commented on lib/room.cpp
> +        QList<const StateEventBase*>* vals = new QList<const StateEventBase*>();
```suggestion
        QVector<const StateEventBase*> vals;
```

2021-11-21 15:44 UTC, KitsuneRal commented on lib/room.cpp
> +            const StateEventBase* val = it.value();
```suggestion
        for (const auto* val: currentState) {
```

2021-11-27 10:22 UTC, KitsuneRal approved these changes
Thanks!

2021-11-27 10:23 UTC, merged