Add autotest for key verification and fix several edge-cases
quotient-im/libQuotient pull request #568
Opened 2022-09-06 19:36 UTC by TobiasFella

2022-09-06 19:41 UTC, CarlSchwan approved these changes
:heart:

2022-09-09 12:27 UTC, KitsuneRal requested changes
I trust you with the logic but suggest a couple of simplifications.

2022-09-09 12:27 UTC, KitsuneRal commented on lib/keyverificationsession.h
> +    }
```suggestion
    bool operator==(const EmojiEntry& rhs) const = default;
```

2022-09-09 12:27 UTC, KitsuneRal commented on autotests/testkeyverification.h
> +
You don't need to add a separate `.h` file here; instead, just define the class in `testkeyverification.cpp` and `#include "testverification.moc"` at the end of it (moc will auto-generate it) - see how it's done in `quotest.cpp`.

2022-09-11 20:07 UTC, KitsuneRal approved these changes

2022-09-12 20:02 UTC, merged