Build with
quotient-im/libQuotient pull request #620
Opened 2023-02-11 17:16 UTC by TobiasFella

-DQT_NO_CAST_TO_ASCII
    -DQT_NO_CAST_FROM_ASCII
    -DQT_NO_URL_CAST_FROM_STRING
    -DQT_NO_CAST_FROM_BYTEARRAY
    -DQT_USE_QSTRINGBUILDER
    -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT
    -DQT_NO_FOREACH

2023-02-11 17:17 UTC, TobiasFella commented
cc @vkrause

2023-02-11 20:41 UTC, KitsuneRal requested changes
I only looked through a half of the PR but overall, please:
- is it possible to use Unicode C++ literals instead of `QLatin1Char`?
- please use `fromLatin1()` wherever the string can be confirmed to be Latin-1 - `fromUtf8()` is much heavier.

2023-02-11 20:41 UTC, KitsuneRal commented on autotests/testolmutility.cpp
> +    QCOMPARE(QString::fromUtf8(olm_utility_last_error(utility)), "SUCCESS"_ls);
I would rather replace the whole test with the code-based one that modern Olm supports:
```suggestion
    QCOMPARE(olm_utility_last_error_code(utility), OLM_SUCCESS);
```

2023-02-11 20:41 UTC, KitsuneRal commented on autotests/testkeyverification.cpp
> +        session->handleEvent(KeyVerificationKeyEvent(transactionId, QString::fromUtf8(keyBytes)));
Those bytes are Base64-encoded.
```suggestion
        session->handleEvent(KeyVerificationKeyEvent(transactionId, QString::fromLatin1(keyBytes)));
```

2023-02-11 20:41 UTC, KitsuneRal commented on CMakeLists.txt
> +add_definitions(
```suggestion
add_compile_definitions(
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/avatar.cpp
> +    if (!url.isValid() || url.scheme() != "mxc"_ls || url.path().count(QLatin1Char('/')) != 1) {
Wouldn't
```suggestion
    if (!url.isValid() || url.scheme() != "mxc"_ls || url.path().count(u'/') != 1) {
```
work instead?

2023-02-11 20:41 UTC, KitsuneRal commented on lib/avatar.cpp
> +    return cachePath % _url.authority() % QLatin1Char('_') % _url.fileName() % ".png"_ls;
Ditto.
```suggestion
    return cachePath % _url.authority() % u'_' % _url.fileName() % ".png"_ls;
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/connection.cpp
> +                std::make_pair(QString::fromUtf8(*expectedMessage), QString::fromUtf8(session.sessionId()));
I'd rather make `doDecryptMessage()` and the first `sessionDecryptMessage()` return `std::pair<QByteArray, QByteArray>`, because:
1. The second `sessionDecryptMessage()` now calls `toUtf8()` on the decrypted payload (the pair's `first`) anyway - basically, there's an unnecessary UTF-8-to-QString-to-UTF8 conversion right now.
2. The Olm session Id (`second`) is known to be Latin-1; instead of carrying `QString` around I'd rather carry `QByteArray` and only convert it to `QString` when really necessary.

2023-02-11 20:41 UTC, KitsuneRal commented on lib/connection.cpp
> +        for (const auto& session : olmSessions[QString::fromUtf8(senderKey)])
Too many conversions of the same `senderKey`. Can you just change the parameter name to `QString` and do `QString::fromUtf8()` once? And while we're at it - this should be `fromLatin1()` rather, I guess?

2023-02-11 20:41 UTC, KitsuneRal commented on lib/connection.cpp
> +            encryptedEvent.ciphertext(QString::fromUtf8(identityKey));
The keys are Base64-encoded.
```suggestion
            encryptedEvent.ciphertext(QString::fromLatin1(identityKey));
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/connection.cpp
> +                     QString::fromUtf8(loginToken), deviceId, initialDeviceName);
```suggestion
                     QString::fromLatin1(loginToken), deviceId, initialDeviceName);
```
But in fact we have to switch `loginToken` back to `QString` because the SSO code calls this after retrieving the token as `QString` (calling `toLatin1()` to accommodate).

2023-02-11 20:41 UTC, KitsuneRal commented on lib/connection.cpp
> +    q->setObjectName(data->userId() % QLatin1Char('/') % data->deviceId());
```suggestion
    q->setObjectName(data->userId() % u'/' % data->deviceId());
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/connection.cpp
> +    if (userId.startsWith(QLatin1Char('@')) && userId.indexOf(QLatin1Char(':')) != -1) {
```suggestion
    if (userId.startsWith(u'@') && userId.indexOf(u':') != -1) {
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/connection.cpp
> +                        << QStringList(q->ignoredUsers().values()).join(QLatin1Char(','));
```suggestion
                        << QStringList(q->ignoredUsers().values()).join(u',');
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/connection.cpp
> +    auto idParts = mediaId.split(QLatin1Char('/'));
```suggestion
    auto idParts = mediaId.split(u'/');
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/connection.cpp
> +                                    QString::fromUtf8(generateTxnId()), contents);
```suggestion
                                    QString::fromLatin1(generateTxnId()), contents);
```
And, looking at the hideous back and forth in `sendMessage()`, I tend to think that `generateTxnId()` has to return `QString` in 0.8.

2023-02-11 20:41 UTC, KitsuneRal commented on lib/connection.cpp
> +    return callApi<SendMessageJob>(roomId, event.matrixType(), QString::fromUtf8(txnId),
```suggestion
    return callApi<SendMessageJob>(roomId, event.matrixType(), QString::fromLatin1(txnId),
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/connection.cpp
> +QString Connection::domain() const { return userId().section(QLatin1Char(':'), 1); }
```suggestion
QString Connection::domain() const { return userId().section(u':', 1); }
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/connection.cpp
> +    if (!uId.startsWith(QLatin1Char('@')) || serverPart(uId).isEmpty()) {
```suggestion
    if (!uId.startsWith(u'@') || serverPart(uId).isEmpty()) {
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/connection.cpp
> +    return stateCacheDir().path() % QLatin1Char('/');
```suggestion
    return stateCacheDir().path() % u'/';
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/connection.cpp
> +    safeUserId.replace(QLatin1Char(':'), QLatin1Char('_'));
```suggestion
    safeUserId.replace(u':', u'_');
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/connection.cpp
> +    olmSessions[QString::fromUtf8(recipientCurveKey)].push_back(std::move(*session));
You can clearly see just a few lines above that `recipientCurveKey` is in Latin-1.
```suggestion
    saveSession(*session, QString::fromLatin1(recipientCurveKey));
    olmSessions[QString::fromLatin1(recipientCurveKey)].push_back(std::move(*session));
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/connection.cpp
> +                             QString::fromUtf8(olmAccount->identityKeys().ed25519) } });
```suggestion
                             QString::fromLatin1(olmAccount->identityKeys().ed25519) } });
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/connection.cpp
> +    return EncryptedEvent(encrypted, QString::fromUtf8(olmAccount->identityKeys().curve25519))
```suggestion
    return EncryptedEvent(encrypted, QString::fromLatin1(olmAccount->identityKeys().curve25519))
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/connection.cpp
> +                                                       QString::fromUtf8(sessionKey))
```suggestion
                                                       roomId, QString::fromLatin1(sessionId),
                                                       QString::fromLatin1(sessionKey))
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/connectiondata.cpp
> +    QString id() const { return userId + QLatin1Char('/') + deviceId; }
```suggestion
    QString id() const { return userId + u'/' + deviceId; }
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/connectiondata.cpp
> +    qCDebug(MAIN) << "Jobs for" << (d->userId + "/"_ls + d->deviceId)
```suggestion
    qCDebug(MAIN) << "Jobs for" << (d->userId + u'/' + d->deviceId)
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/converters.h
> +            result.insert(offset, QLatin1Char('_')); // NB: invalidates iterators
```suggestion
            result.insert(offset, u'_'); // NB: invalidates iterators
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/converters.h
> +        q.addQueryItem(k, QString::fromUtf8(v.toEncoded()));
It's URL-encoded, so no Unicode.
```suggestion
        q.addQueryItem(k, QString::fromLatin1(v.toEncoded()));
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/database.cpp
> +    dbDir.replace(QLatin1Char(':'), QLatin1Char('_'));
```suggestion
    dbDir.replace(u':', u'_');
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/database.cpp
> +                                % QLatin1Char('/') % dbDir };
```suggestion
                                % u'/' % dbDir };
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/e2ee/e2ee_common.h
> +                                                    QString::fromUtf8(signature) } } } } } }
Signatures are Base64.
```suggestion
                                                    QString::fromLatin1(signature) } } } } } }
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/e2ee/qolmaccount.cpp
> +               { "ed25519:"_ls + m_deviceId, QString::fromUtf8(idKeys.ed25519) } },
```suggestion
        .keys{ { "curve25519:"_ls + m_deviceId, QString::fromLatin1(idKeys.curve25519) },
               { "ed25519:"_ls + m_deviceId, QString::fromLatin1(idKeys.ed25519) } },
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/e2ee/qolmaccount.cpp
> +            { m_userId, { { "ed25519:"_ls + m_deviceId, QString::fromUtf8(signIdentityKeys()) } } } }
```suggestion
            { m_userId, { { "ed25519:"_ls + m_deviceId, QString::fromLatin1(signIdentityKeys()) } } } }
```

2023-02-11 20:41 UTC, KitsuneRal commented on lib/e2ee/qolmaccount.cpp
> +QString QOlmAccount::accountId() const { return m_userId % QLatin1Char('/') % m_deviceId; }
```suggestion
QString QOlmAccount::accountId() const { return m_userId % u'/' % m_deviceId; }
```

2023-02-13 17:24 UTC, TobiasFella commented
- Ported to u''
- Switched to QString::fromLatin1, whenever possible, i think

2023-02-13 19:04 UTC, KitsuneRal commented
Something's going really wrong in CI after your updates - see the logs.

2023-02-15 13:19 UTC, KitsuneRal commented
Still not quite there.

2023-02-15 13:20 UTC, KitsuneRal commented
Fat fingers, sorry

2023-02-18 18:59 UTC, KitsuneRal requested changes
A few more brush-ups

2023-02-18 18:59 UTC, KitsuneRal commented on lib/events/roommessageevent.cpp
> +            json[BodyKeyL] = QString("* "_ls + plainBody);
```suggestion
            json[BodyKeyL] = "* "_ls + plainBody;
```

2023-02-18 18:59 UTC, KitsuneRal commented on lib/keyverificationsession.cpp
> +    commitment = commitment.left(commitment.indexOf(u'='));
`toLatin1()` and `fromLatin1` in the same expression - this doesn't look right.
```suggestion
    const auto canonicalEvent = QJsonDocument(event.contentJson()).toJson(QJsonDocument::Compact);
    auto commitment = QCryptographicHash::hash(publicKey + canonicalEvent, QCryptographicHash::Sha256).toBase64(QByteArray::OmitTrailingEquals);
```

2023-02-18 18:59 UTC, KitsuneRal commented on lib/room.cpp
> +    connection()->callApi<RedactEventJob>(id(), QString::fromUtf8(QUrl::toPercentEncoding(eventId)),
Upfront percent-encoding of request parameters is deprecated since libQuotient 0.7 - `toPercentEncoding()` shouldn't even have been here.
```suggestion
    connection()->callApi<RedactEventJob>(id(), eventId),
```

2023-02-18 18:59 UTC, KitsuneRal commented on lib/uri.cpp
> +    auto fragment = QString("/"_ls + primaryId());
```suggestion
    auto fragment = u'/' + primaryId();
```

2023-02-18 18:59 UTC, KitsuneRal commented on lib/uri.cpp
> +        fragment += QString("/"_ls + secId);
```suggestion
        fragment += u'/' + secId;
```

2023-02-18 18:59 UTC, KitsuneRal commented on lib/uri.cpp
> +        fragment += QString("?"_ls + q);
```suggestion
        fragment += u'?' + q;
```

2023-02-18 18:59 UTC, KitsuneRal commented on quotest/quotest.cpp
> +    const auto newTopic = QString::fromUtf8(connection()->generateTxnId()); // Just a way to make
```suggestion
    const auto newTopic = QString::fromLatin1(connection()->generateTxnId()); // Just a way to make
```

2023-02-18 18:59 UTC, KitsuneRal commented on quotest/quotest.cpp
> +        const auto& newName = QString::fromUtf8(connection()->generateTxnId()); // See setTopic()
```suggestion
        const auto& newName = QString::fromLatin1(connection()->generateTxnId()); // See setTopic()
```

2023-02-18 18:59 UTC, KitsuneRal commented on quotest/quotest.cpp
> +        QString::fromUtf8(QUrl::toPercentEncoding(joinRoomAlias.mid(1), QByteArrayLiteral(":")));
```suggestion
        QString::fromLatin1(QUrl::toPercentEncoding(joinRoomAlias.mid(1), QByteArrayLiteral(":")));
```

2023-02-18 18:59 UTC, KitsuneRal commented on quotest/quotest.cpp
> +                            return QString(q + "&via="_ls + s);
```suggestion
                            return q + "&via="_ls + s;
```

2023-02-18 19:00 UTC, KitsuneRal commented
The whole PR really warrants a more careful review to see how the API should be changed in 0.8 so that more of those conversions are not necessary. But that's for another day (or rather week).

2023-02-24 16:56 UTC, KitsuneRal commented on lib/room.cpp
> +    connection()->callApi<RedactEventJob>(id(), eventId),
Typo in the previous suggestion
```suggestion
    connection()->callApi<RedactEventJob>(id(), eventId,
```

2023-02-24 16:56 UTC, KitsuneRal commented on lib/room.cpp
> +                                          QString::fromUtf8(connection()->generateTxnId()), reason);
```suggestion
                                          QString::fromLatin1(connection()->generateTxnId()), reason);
```

2023-02-24 17:10 UTC, KitsuneRal commented on lib/keyverificationsession.cpp
> +    auto commitment = QCryptographicHash::hash(publicKey + canonicalEvent, QCryptographicHash::Sha256).toBase64(QByteArray::OmitTrailingEquals);
I hunted after conversions too aggressively in the previous suggestion.
```suggestion
    const auto commitment =
        QString::fromLatin1(QCryptographicHash::hash(publicKey + canonicalEvent,
                                                     QCryptographicHash::Sha256)
                                .toBase64(QByteArray::OmitTrailingEquals));
```

2023-02-24 21:26 UTC, merged