Direct Chat Encryption Default
quotient-im/libQuotient pull request #730
Opened 2024-04-02 17:27 UTC by nvrWhere

Add the ability to both set whether connections will try to encrypt direct chats by default and change the setting for individual connections

2024-04-04 06:10 UTC, KitsuneRal requested changes
I agree with the approach, see fixups below.

2024-04-04 06:10 UTC, KitsuneRal commented on Quotient/connection.cpp
> +        });
```suggestion
        initialStateEvents.append({ EncryptionEvent::TypeId, encryptionContent.toJson() });
```

2024-04-04 06:10 UTC, KitsuneRal commented on Quotient/connection.cpp
> +    emit directChatsEncryptionChanged(enable);
Did you accidentally swap the two signals, here and in `enableDirectChatEncryption()`?

2024-04-04 10:11 UTC, nvrWhere commented on Quotient/connection.cpp
> +    emit directChatsEncryptionChanged(enable);
Yes should pay more attention to autofills

2024-04-06 08:01 UTC, KitsuneRal commented on Quotient/connection.cpp
> +    emit directChatsEncryptionChanged(enable);
```suggestion
    emit encryptionChanged(enable);
```
:D

2024-04-06 08:04 UTC, KitsuneRal approved these changes

2024-04-06 08:04 UTC, merged