Add helper functions for replies and threads to RoomMessageEvent
quotient-im/libQuotient pull request #789
Opened 2024-08-27 15:56 UTC by nvrWhere

These can be used to check if the message is a reply or part of a thread and then get the relevant event ID.

For replies there are 2 functions because threads uses replies as the fallback for non-threaded clients. The function `isReplyIncludingFallbacks` should be used for a non-thread aware client.

This is more upstream based on NeoChat that we've found useful.

2024-08-28 10:16 UTC, KitsuneRal commented on Quotient/events/roommessageevent.cpp
> +    return false;
Add `bool isFallingBack;` to `EventRelation`, add it to `JsonConverter<EventRelation>`, and then the following can be here:
```suggestion
    const auto relation = getUpstreamRelation();
    return relation && relation.type == EventRelation::ReplyType && !relation.isFallingBack;
```

2024-08-28 11:15 UTC, KitsuneRal requested changes, later dismissed
Overall, this would be great to have but it would really do with using native structures throughout. I realise that the current `RoomMessageEvent` API is not that convenient so I'd start with making the following method:
```cplusplus
std::optional<EventRelation> RoomMessageEvent::relatesTo() const
{
    return content() && hasTextContent() ? static_cast<const TextContent*>(content())->relatesTo
                                         : std::nullopt_t;
}
```
and then use it to implement the rest, as below. But I'm open for discussion.

2024-08-28 11:15 UTC, KitsuneRal commented on Quotient/events/roommessageevent.cpp
> +    return false;
Add `bool isFallingBack = false;` to `EventRelation`, add it to `JsonConverter<EventRelation>`, and then the following can be here:
```suggestion
    const auto relation = relatesTo();
    return relation && relation.type == EventRelation::ReplyType && !relation.isFallingBack;
```

2024-08-28 11:15 UTC, KitsuneRal commented on Quotient/events/roommessageevent.cpp
> +    return contentPart<QJsonObject>("m.relates_to"_ls).contains("m.in_reply_to"_ls);
```suggestion
    const auto relation = relatesTo();
    return relation && relation->type == EventRelation::ReplyType;
```

2024-08-28 11:15 UTC, KitsuneRal commented on Quotient/events/roommessageevent.cpp
> +            || (!unsignedPart<QJsonObject>("m.relations"_ls).isEmpty() && unsignedPart<QJsonObject>("m.relations"_ls).contains("m.thread"_ls));
Add `EventRelation::ThreadType` next to other types, then:
```suggestion
    const auto relation = getUpstreamRelation();
    return (relation && relation.type == EventRelation::ThreadType)
            || unsignedPart<QJsonObject>("m.relations"_ls).contains(EventRelation::ThreadType);
```
You are not winning anything if you check `m.relations` for emptiness first; `QJsonObject::contains()` will almost always catch that case and exit early.

2024-08-28 11:15 UTC, KitsuneRal commented on Quotient/events/roommessageevent.cpp
> +    }
```suggestion
    if (const auto relation = relatedTo(); relation && relation.type == EventRelation::ThreadType)
        return relation.eventId;
```

2024-08-28 11:15 UTC, KitsuneRal commented on Quotient/events/roommessageevent.cpp
> +    if (!unsignedPart<QJsonObject>("m.relations"_ls).isEmpty() && unsignedPart<QJsonObject>("m.relations"_ls).contains("m.thread"_ls)) {
Same as above.
```suggestion
    if (unsignedPart<QJsonObject>("m.relations"_ls).contains(EventRelation::ThreadType)) {
```

2024-08-28 11:15 UTC, KitsuneRal commented on Quotient/events/roommessageevent.cpp
> +}
I would go with something more generic here. I don't quite like "parent" and "child" event naming the spec uses, but I can accept it as well if my suggestion doesn't ring true.
```suggestion
QString RoomMessageEvent::upstreamEventId() const
{
    const auto relation = relatesTo();
    return relation ? relation.eventId : QString();
}
```

2024-08-28 11:15 UTC, KitsuneRal commented on Quotient/events/roommessageevent.h
> +    QString replyEventId()const;
```suggestion
    QString upstreamEventId() const;
```

2024-08-28 18:40 UTC, nvrWhere commented
> Overall, this would be great to have but it would really do with using native structures throughout. I realise that the current `RoomMessageEvent` API is not that convenient so I'd start with making the following method:
> 
> ```
> std::optional<EventRelation> RoomMessageEvent::relatesTo() const
> {
>     return content() && hasTextContent() ? static_cast<const TextContent*>(content())->relatesTo
>                                          : std::nullopt_t;
> }
> ```
> 
> and then use it to implement the rest, as below. But I'm open for discussion.

I'm happy with the general strategy although what are your thoughts on adding fallback data to `EventRelation` for threads because as it stands without some serious thought your version of `isReplyIncludingFallbacks` would still return false for non-thread aware clients as the `EventRelation` would have the type `EventRelation::ThreadType`.

So from my perspective we have two choices:
1. Setup `EventRelation` so that it always treats a threaded reply as m.thread only and look at the JSON in `isReplyIncludingFallbacks` 
2. Rework `EventRelation` so it can handle both cases elegantly somehow

1 I think is definitely easier.

2024-08-29 17:24 UTC, nvrWhere commented
OK so I think I manged to implement 2. but it's a lot more involved than your initial comments.

EventRelation needs to be setup to handle fallback event IDs as well as fallbacks. Basically when an event is threaded `eventId` get filled with the threadroot, therefore we need an additional param to hold the `fallbackEventId` in that case.

Next I had to re-work `JsonObjectConverter<EventRelation>::dumpTo` and `JsonObjectConverter<EventRelation>::fillFrom` to make sure that everything was filled nicely for both replies an threads. In a reply `eventId` has the event ID that was replied to in a thread that goes in `fallbackEventId` and `eventId` get the threadroot as noted above.

For `RoomMessageEvent` I added `upstreamEventId()` in addition to `replyEventId()` as `upstreamEventId()` will only work well for certain relations, see the comments. I also had to do threadRootEventId() slightly differently to make sure it return the correct ID on the root event itself.

Take a look tell me what you think.

2024-08-29 19:22 UTC, KitsuneRal commented
Okay, I really didn't think that fallbacks are complicated, will take a deeper look separately. Thanks for taking a shot.

2024-09-12 06:46 UTC, KitsuneRal reviewed
Finally got to re-reviewing this. Okay, so as I understand it, I overlooked that fallbacks need an extra event id that may be different to thread root (why did we at SCT complicate things? anyways...). Looking on now.

2024-09-15 16:44 UTC, KitsuneRal reviewed
Ok, I wrapped my head around the subject and paged in all the relevant spec pieces - I generally am happy with the direction even though `EventRelation` becomes more "denormalised" with it. Suggest to rename `fallbackEventId` to something that better explains its purpose (it's not only for fallbacks after all); and have a couple of comments on top.

2024-09-15 16:44 UTC, KitsuneRal commented on Quotient/events/roommessageevent.cpp
> +    return {};
```suggestion
    } else
        return unsignedPart<QJsonObject>("m.relations"_ls)[EventRelation::ThreadType].toString();
```

2024-09-15 16:44 UTC, KitsuneRal commented on Quotient/events/eventrelation.h
> +    QString fallbackEventId = {};
```suggestion
    QString inThreadReplyEventId = {};
```

2024-09-15 16:44 UTC, KitsuneRal commented on Quotient/events/eventrelation.h
> +    }
```suggestion
    static EventRelation replyInThread(QString threadRootId, bool isFallingBack, QString inThreadReplyEventId)
    {
        return { ThreadType, std::move(threadRootId), {}, std::move(isFallingBack), std::move(inThreadReplyEventId) };
    }
```

2024-09-15 16:44 UTC, KitsuneRal commented on Quotient/events/eventrelation.cpp
> +        fromJson(replyJson[EventIdKey], pod.fallbackEventId);
```suggestion
        fromJson(replyJson[EventIdKey], pod.inThreadReplyEventId);
```

2024-09-15 16:44 UTC, KitsuneRal commented on Quotient/events/eventrelation.cpp
> +        jo.insert(EventRelation::ReplyType, {{EventIdKey, pod.fallbackEventId}});
```suggestion
        jo.insert(EventRelation::ReplyType, {{EventIdKey, pod.inThreadReplyEventId}});
```

2024-09-15 16:44 UTC, KitsuneRal commented on Quotient/events/roommessageevent.cpp
> +            return relation.value().fallbackEventId;
```suggestion
            return relation.value().inThreadReplyEventId;
```

2024-09-15 16:44 UTC, KitsuneRal commented on Quotient/events/roommessageevent.cpp
> +            return relation.value().fallbackEventId;
```suggestion
            return relation.value().inThreadReplyEventId;
```

2024-09-15 16:44 UTC, KitsuneRal commented on Quotient/events/roommessageevent.h
> +    bool isReplyIncludingFallbacks() const;
Would it make sense to wrap this up into `isReply()` by adding `includeFallbacks` argument? Possibly with a default value (`false`? not sure about this).

2024-09-15 16:44 UTC, KitsuneRal commented on Quotient/events/roommessageevent.h
> +    QString replyEventIdIncludingFallbacks()const;
Ditto

2024-09-17 18:25 UTC, nvrWhere commented on Quotient/events/roommessageevent.h
> +    bool isReplyIncludingFallbacks() const;
So interestingly this is actually how I had it in the NeoChat function this is based off and I have no idea why I unrolled it so I agree and have added the param and compressed the functions

2024-09-18 06:01 UTC, KitsuneRal approved these changes
Thanks a ton!

2024-09-18 06:02 UTC, merged