Don't warn about unsupported RoomType values
quotient-im/libQuotient pull request #822
Opened 2024-11-02 01:06 UTC by redstrate

enumFromJsonString is changed to return a std::optional, and lets the callee handle returning a default value and warning if they want to.

Fixes #790

2024-11-02 14:11 UTC, KitsuneRal commented on Quotient/events/roomcreateevent.cpp
> +    return enumFromJsonString<RoomType>(jv.toString(), RoomTypeStrings).or_else([] -> std::optional<RoomType> { return RoomType::Undefined; }).value();
```suggestion
    return enumFromJsonString<RoomType>(jv.toString(), RoomTypeStrings).value_or(RoomType::Undefined);
```

2024-11-02 14:19 UTC, KitsuneRal requested changes
Can you apply the same change to `flagFromJsonString()` too, please (and change `JsonConverter<Membership>` accordingly, dropping the warning from it too)?

2024-11-02 16:06 UTC, redstrate commented on Quotient/events/roomcreateevent.cpp
> +    return enumFromJsonString<RoomType>(jv.toString(), RoomTypeStrings).or_else([] -> std::optional<RoomType> { return RoomType::Undefined; }).value();
even better, thanks

2024-11-02 16:07 UTC, redstrate commented
> Can you apply the same change to `flagFromJsonString()` too, please (and change `JsonConverter<Membership>` accordingly, dropping the warning from it too)?

That kills all usage of `_impl::warnUnknownEnumValue`, should I kill that or keep it?

2024-11-02 17:57 UTC, KitsuneRal commented
> > Can you apply the same change to `flagFromJsonString()` too, please (and change `JsonConverter<Membership>` accordingly, dropping the warning from it too)?
> 
> Done. That's the last usage of `_impl::warnUnknownEnumValue`, should I kill that or keep it?

Kill it!

2024-11-05 22:36 UTC, redstrate commented
> Kill it!

It's dead now!

2024-11-06 07:32 UTC, KitsuneRal commented
> > Kill it!
> 
> It's dead now!

It has ceased to be! It's expired and gone to meet it's maker! Bereft of life, it rests in peace! This is an ex-function!

2024-11-06 07:33 UTC, KitsuneRal approved these changes

2024-11-06 07:33 UTC, merged